import { Check, ChevronRight, Eye, Layers3, Monitor, MousePointer2, Smartphone, Sparkles } from "lucide-react";

const sections = ["Navigation", "Hero", "Selected work", "About studio", "Contact"];

export default function StudioSection() {
  return (
    <section id="studio" className="relative overflow-hidden bg-[#eef2ff] px-5 py-28 text-[#0a1420] sm:px-8 lg:py-40">
      <div className="absolute -right-56 top-20 size-[620px] rounded-full border-[100px] border-blue-600/7" />
      <div className="absolute inset-0 opacity-35 [background-image:linear-gradient(rgba(39,83,220,.09)_1px,transparent_1px),linear-gradient(90deg,rgba(39,83,220,.09)_1px,transparent_1px)] [background-size:80px_80px]" />
      <div className="relative mx-auto max-w-[1320px]">
        <div data-reveal className="flex flex-col justify-between gap-8 lg:flex-row lg:items-end"><div><p className="text-xs font-semibold uppercase tracking-[.22em] text-blue-700">The Lestow studio</p><h2 className="mt-7 max-w-4xl text-[clamp(3.1rem,6.5vw,6.5rem)] font-semibold leading-[.9] tracking-[-.07em]">Direct the canvas. <span className="text-blue-700">Keep your system.</span></h2></div><p className="max-w-sm text-sm leading-6 text-[#0a1420]/55">A visual workspace where your judgment and Lestow&apos;s AI team shape every page together in real time.</p></div>

        <div data-reveal data-studio-frame className="relative mt-20 rounded-[2rem] bg-[#0a1420] p-3 shadow-[0_45px_110px_rgba(29,48,109,.28)] sm:p-5">
          <div className="flex h-12 items-center justify-between px-2 text-white/50 sm:px-3"><div className="flex items-center gap-3"><span className="size-2 rounded-full bg-[#b9ff66]" /><span className="text-[10px] uppercase tracking-[.16em]">North Studio / Homepage</span></div><div className="flex items-center gap-2"><span className="hidden rounded-lg border border-white/10 px-3 py-2 text-[10px] sm:block">Preview</span><span className="rounded-lg bg-[#b9ff66] px-3 py-2 text-[10px] font-semibold text-[#0a1420]">Publish</span></div></div>
          <div className="grid min-h-[610px] overflow-hidden rounded-[1.3rem] bg-[#e9e7df] lg:grid-cols-[220px_1fr_250px]">
            <aside data-studio-panel className="hidden border-r border-black/10 bg-[#f7f6f1] p-4 lg:block"><p className="text-[10px] font-semibold uppercase tracking-[.15em] text-black/40">Page structure</p><div className="mt-5 space-y-2">{sections.map((item, index) => <div key={item} className={`flex items-center gap-3 rounded-xl px-3 py-3 text-xs ${index === 1 ? "bg-white shadow-sm" : "text-black/50"}`}><Layers3 size={14} />{item}{index === 1 && <ChevronRight size={13} className="ml-auto" />}</div>)}</div></aside>

            <div data-studio-canvas className="relative overflow-hidden p-4 sm:p-7"><div className="mx-auto min-h-[520px] max-w-3xl overflow-hidden rounded-xl bg-[#d5d0c4] shadow-2xl"><div className="flex items-center justify-between bg-[#171915] px-5 py-4 text-white"><span className="text-sm font-semibold">NORTH°</span><div className="flex gap-4 text-[9px] uppercase tracking-[.14em] text-white/55"><span>Work</span><span>Studio</span><span>Contact</span></div></div><div className="relative grid min-h-[460px] content-between overflow-hidden bg-[radial-gradient(circle_at_75%_28%,#b9ff66_0,transparent_28%),linear-gradient(135deg,#ece9df,#beb8aa)] p-7 sm:p-12"><div data-studio-shine className="absolute -left-1/3 top-0 h-full w-1/3 -skew-x-12 bg-gradient-to-r from-transparent via-white/35 to-transparent" /><div className="relative z-10 max-w-xl"><p className="text-[10px] font-semibold uppercase tracking-[.18em]">Independent architecture practice</p><h3 className="mt-8 text-5xl font-semibold leading-[.88] tracking-[-.065em] sm:text-7xl">Spaces made for <span className="italic">living.</span></h3></div><div className="relative z-10 flex items-end justify-between"><p className="max-w-xs text-xs leading-5 text-black/55">Thoughtful homes and public spaces shaped around light, material, and everyday rituals.</p><span className="grid size-12 place-items-center rounded-full bg-black text-white"><MousePointer2 size={17} /></span></div></div></div></div>

            <aside data-studio-panel className="hidden border-l border-black/10 bg-[#f7f6f1] p-4 lg:block"><div className="flex items-center justify-between"><p className="text-[10px] font-semibold uppercase tracking-[.15em] text-black/40">Design agent</p><Sparkles size={14} className="text-blue-700" /></div><div className="mt-5 rounded-xl bg-white p-4 shadow-sm"><p className="text-xs font-medium">Hero section</p><p className="mt-2 text-[10px] leading-4 text-black/45">Balanced editorial layout with a warmer material palette.</p><div className="mt-4 flex gap-2"><span className="size-7 rounded-full bg-[#171915]" /><span className="size-7 rounded-full bg-[#b9ff66]" /><span className="size-7 rounded-full bg-[#d5d0c4]" /></div></div><div className="mt-3 space-y-2">{["Copy aligned", "Contrast passed", "Mobile optimized"].map(item => <div key={item} className="flex items-center gap-2 rounded-lg border border-black/8 px-3 py-2.5 text-[10px] text-black/55"><Check size={12} className="text-emerald-600" />{item}</div>)}</div><div className="mt-4 flex justify-center gap-2"><Monitor size={14} /><Smartphone size={14} className="text-black/30" /><Eye size={14} className="ml-auto" /></div></aside>
          </div>
          <div data-studio-float className="absolute -left-4 top-[38%] hidden items-center gap-3 rounded-xl border border-blue-100 bg-white px-4 py-3 text-xs font-medium text-blue-950 shadow-xl xl:flex"><span className="grid size-8 place-items-center rounded-lg bg-blue-600 text-white"><Sparkles size={14} /></span>AI rewrite complete</div>
          <div data-studio-float className="absolute -right-5 bottom-[22%] hidden items-center gap-3 rounded-xl border border-blue-100 bg-white px-4 py-3 text-xs font-medium text-blue-950 shadow-xl xl:flex"><Check size={14} className="text-emerald-600" />Mobile layout passed</div>
        </div>
      </div>
    </section>
  );
}
